# Generated by Django 4.1 on 2022-09-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyBlog", "0008_remove_post_home_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="description",),
        migrations.AlterField(
            model_name="post", name="content", field=models.TextField(blank=True),
        ),
    ]
